version: "3.8"

services:
  database:
    platform: linux/x86_64
    image: mysql:8.0.28
    environment:
      - MYSQL_DATABASE=soccer
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '127.0.0.1:3306:3306'
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

  soccer-manager:
    image: dobschal/soccer-manager
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
