import { describe, it, expect, vi, beforeEach } from 'vitest'

vi.mock('../../lib/gateway.js', () => ({
  server: {
    getGameReport: vi.fn(),
    createGameReport: vi.fn()
  },
  showServerError: vi.fn()
}))

vi.mock('../../partials/toast.js', () => ({
  toast: vi.fn()
}))

import { GameReport } from '../../partials/gameReport.js'
import { server } from '../../lib/gateway.js'

describe('GameReport', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  describe('template', () => {
    it('offers the generate button when no report exists yet', () => {
      const element = new GameReport({ gameId: 1 })
      const html = element.template

      expect(html).toContain('game-report-generate')
      expect(html).toContain('Create match report')
      expect(html).not.toContain('ui-element-loading-ball')
    })

    it('shows the loading ball and the generating message while working', () => {
      const element = new GameReport({ gameId: 1 })
      element.isGenerating = true
      const html = element.template

      expect(html).toContain('ui-element-loading-ball')
      expect(html).toContain('Match report is being created...')
      expect(html).not.toContain('game-report-generate')
    })

    it('renders the report as paragraphs with a disclaimer', () => {
      const element = new GameReport({ gameId: 1 })
      element.reportText = 'First paragraph.\n\nSecond paragraph.'
      const html = element.template

      expect(html).toContain('<p>First paragraph.</p>')
      expect(html).toContain('<p>Second paragraph.</p>')
      expect(html).toContain('generated by an AI')
      expect(html).not.toContain('game-report-generate')
    })

    it('escapes model output so it cannot inject markup', () => {
      const element = new GameReport({ gameId: 1 })
      element.reportText = '<img src=x onerror="alert(1)">'
      const html = element.template

      expect(html).not.toContain('<img src=x')
      expect(html).toContain('&lt;img src=x')
    })

    it('renders an error message above the retry button', () => {
      const element = new GameReport({ gameId: 1 })
      element.errorMessage = 'Too many match reports requested.'
      const html = element.template

      expect(html).toContain('alert-warning')
      expect(html).toContain('Too many match reports requested.')
      expect(html).toContain('game-report-generate')
    })

    it('renders an empty placeholder root when the feature is unavailable and nothing is stored', () => {
      const element = new GameReport({ gameId: 1 })
      element.isAvailable = false
      const html = element.template

      expect(html).toContain('game-report-hidden')
      expect(html).not.toContain('game-report-generate')
      // A UIElement must always render exactly one root node.
      const wrapper = document.createElement('template')
      wrapper.innerHTML = html
      expect(wrapper.content.children.length).toBe(1)
    })

    it('still shows a stored report when the feature was switched off', () => {
      const element = new GameReport({ gameId: 1 })
      element.isAvailable = false
      element.reportText = 'Stored report.'
      expect(element.template).toContain('Stored report.')
    })
  })

  describe('load', () => {
    it('adopts a stored report without triggering generation', async () => {
      server.getGameReport.mockResolvedValueOnce({
        report: { text: 'stored', model: 'm' },
        available: true
      })

      const element = new GameReport({ gameId: 42 })
      await element.load(false)

      expect(server.getGameReport).toHaveBeenCalledWith(42)
      expect(server.createGameReport).not.toHaveBeenCalled()
      expect(element.reportText).toBe('stored')
    })

    it('leaves the button visible when nothing is stored', async () => {
      server.getGameReport.mockResolvedValueOnce({ report: null, available: true })

      const element = new GameReport({ gameId: 42 })
      await element.load(false)

      expect(element.reportText).toBeNull()
      expect(element.isAvailable).toBe(true)
    })

    it('survives a failing lookup', async () => {
      server.getGameReport.mockRejectedValueOnce(new Error('offline'))

      const element = new GameReport({ gameId: 42 })
      await expect(element.load(false)).resolves.toBeUndefined()
      expect(element.reportText).toBeNull()
    })
  })

  describe('events', () => {
    it('marks the generate button optional so states without it can be applied', () => {
      // The loading and the finished-report state don't render the button —
      // a required selector made update() throw "Cannot apply event listener".
      const element = new GameReport({ gameId: 1 })
      expect(Object.keys(element.events)).toEqual(['(optional).game-report-generate'])
    })
  })

  describe('generate button', () => {
    it('stores the generated text and clears the loading state', async () => {
      server.createGameReport.mockResolvedValueOnce({ report: { text: 'fresh report', model: 'm' } })
      const element = new GameReport({ gameId: 42 })
      element.update = vi.fn()

      await element.events['(optional).game-report-generate'].click()

      expect(server.createGameReport).toHaveBeenCalledWith(42)
      expect(element.reportText).toBe('fresh report')
      expect(element.isGenerating).toBe(false)
      // Once to show the loading ball, once to show the result.
      expect(element.update).toHaveBeenCalledTimes(2)
    })

    it('keeps the error and drops the loading state when generation fails', async () => {
      server.createGameReport.mockRejectedValueOnce({ message: 'Too many match reports requested.' })
      const element = new GameReport({ gameId: 42 })
      element.update = vi.fn()

      await element.events['(optional).game-report-generate'].click()

      expect(element.errorMessage).toBe('Too many match reports requested.')
      expect(element.reportText).toBeNull()
      expect(element.isGenerating).toBe(false)
    })

    it('ignores a second click while a report is being generated', async () => {
      const element = new GameReport({ gameId: 42 })
      element.update = vi.fn()
      element.isGenerating = true

      await element.events['(optional).game-report-generate'].click()

      expect(server.createGameReport).not.toHaveBeenCalled()
    })
  })
})
