name: Build and push Docker image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: dobschal/soccer-manager:latest
      - name: Install SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Connect to server SSH and update server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd deployments/soccer-manager && docker compose pull && docker compose up -d && exit"
      - name: Clean up
        run: rm -rf ~/.ssh
